title: Glitchlette
description: GLITCHLETTE is a Seattle-based electronic music project by Autumn Marceau.
baseurl: "" # leave blank for root
lang: en-US
url: "https://glitchlette.com" # replace with your domain
